apiVersion: v1
kind: Service
metadata:
  name: zabbix-exporter
  namespace: zabbix-exporter
spec:
  selector:
    app: zabbix-exporter
  type: ClusterIP
  ports:
    - name: http
      port: 9110
      targetPort: http
