apiVersion: v1
kind: Service
metadata:
  name: zabbix-exporter-svc
  namespace: zabbix-exporter
spec:
  selector:
    app: zabbix-exporter
  type: NodePort
  ports:
    - name: http-port
      port: 9110
      targetPort: 9110

